apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: recipes-manager-database
  ports:
    - protocol: TCP
      port: {{ .Values.db.port | default "27017" }}
      targetPort: {{ .Values.db.port | default "27017" }}