apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-manager-database-pv-claim
spec:
  accessModes:
    - ReadWriteMany
#  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.db.size | default "5Gi" }}