apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: recipes-manager-ui-app
  ports:
    - protocol: TCP
      port: {{ .Values.ui.port | default "5000" }}
      targetPort: {{ .Values.ui.port | default "5000" }}