apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recipes-manager-ingress 
spec:
  rules:
  - http:
      paths:              
      - path: /api/v1/recommendation
        pathType: Prefix      
        backend:
          service:
            name: recommendations-service
            port: 
              number: {{ .Values.recommender.port | default "5000" }}            
      - path: /swagger
        pathType: Prefix      
        backend:
          service:
            name: recipes-manager-service
            port: 
              number: {{ .Values.recipesManager.port | default "8080" }}
      - path: /api
        pathType: Prefix      
        backend:
          service:
            name: recipes-manager-service
            port: 
              number: {{ .Values.recipesManager.port | default "8080" }}
      - path: /
        pathType: Prefix      
        backend:
          service:
            name: ui-service
            port: 
              number: {{ .Values.ui.port | default "5000" }}