apiVersion: v1
kind: ConfigMap
metadata:
  name: recipes-manager-config
data:
  recipes-manager-config.yml: |
    recipeDB:
      host: mongodb://db-service:{{ .Values.db.port | default "5000" }}
    drive:
      connection:
        secret:
          file: /etc/recipes-manager-drive/client_secret.json
    log:
      level: {{ .Values.recipesManager.config.log | default "debug" }}
