apiVersion: v1
kind: Service
metadata:
  name: recommendations-service
spec:
  selector:
    app: recipes-recommendation-app
  ports:
    - protocol: TCP
      port: {{ .Values.recommender.port | default "5000" }}
      targetPort: {{ .Values.recommender.port | default "5000" }}